# Generated by Django 6.0.2 on 2026-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('eq', 'earthquake'), ('tsunami', 'tsunami'), ('flood', 'flood'), ('other', 'other')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
