# Generated by Django 6.0.2 on 2026-02-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('locations', '0004_location_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('responded', 'responded'), ('failed', 'failed')], default='sent', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='locations.device')),
            ],
        ),
    ]
