# Generated by Django 6.0.2 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertdelivery'),
        ('locations', '0004_location_alert'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'device'), name='uniq_alert_device'),
        ),
    ]
