# Generated by Django 6.0.2 on 2026-02-25 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertdelivery_uniq_alert_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 2, 25, 2, 44, 39, 482246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
