# Generated by Django 6.0.2 on 2026-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdelivery',
            name='response_code',
            field=models.CharField(blank=True, choices=[('safe', 'safe'), ('need_help', 'need_help'), ('injured', 'injured'), ('unknown', 'unknown')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='response_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
