# Generated by Django 6.0.2 on 2026-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alertdelivery_response_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdelivery',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='resolved_note',
            field=models.TextField(blank=True),
        ),
    ]
