# Generated by Django 6.0.2 on 2026-02-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_pushsubscription'),
        ('push', '0003_migrate_subscriptions'),
    ]

    operations = [
    ]
