# Generated by Django 6.0.2 on 2026-02-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_device_watch_prefecture_code_and_more'),
        ('push', '0004_merge_20260226_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscription', to='locations.device'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DevicePushSubscription',
        ),
    ]
