# Generated by Django 6.0.2 on 2026-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.CharField(choices=[('pre', 'pre-disaster'), ('alert', 'alert'), ('manual', 'manual')], default='manual', max_length=16),
        ),
    ]
