# Generated by Django 6.0.2 on 2026-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
