# Generated by Django 6.0.2 on 2026-02-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('locations', '0003_location_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='alerts.alert'),
        ),
    ]
