# Generated by Django 6.0.2 on 2026-02-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
