# Generated by Django 6.0.2 on 2026-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_device_last_accuracy_device_last_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_latitude', 'last_longitude'], name='idx_device_last_lat_lon'),
        ),
    ]
