# Generated by Django 6.0.2 on 2026-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_device_idx_device_last_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='watch_prefecture_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='device',
            name='watch_prefecture_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='watch_prefecture_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
